image: docker:20.10.10

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERT_DIR: ""
  INTERNAL_IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA

services:
  - docker:20.10.10-dind

stages:
  - build
  - test

default:
  tags:
    - ht-docker

container_scanning:
  variables:
    TRIVY_TIMEOUT: "1h"

include:
  - project: 'security/container-scanning'
    file: '.ESnet-container-scan.yml'

build:
  stage: build
  variables:
    PUBLISH_TAG: $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID-g$CI_COMMIT_SHORT_SHA
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $INTERNAL_IMAGE_TAG -t $PUBLISH_TAG$TAG_SUFFIX .
    # push using the generic internal name so trivy can always find/scan it
    - docker push $INTERNAL_IMAGE_TAG
    # push using a more user friendly name for other repo users of this image
    - docker push $PUBLISH_TAG$TAG_SUFFIX
    - |
      echo Image published as: $PUBLISH_TAG$TAG_SUFFIX
  timeout: 3h
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      variables:
        TAG_SUFFIX: -dev

