image: docker:19.03.8

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERT_DIR: ""
  ESNET_REGISTRY: "hub.es.net:5000"
  RELEASE_BRANCH: "main"
  LATEST_TAG: $ESNET_REGISTRY/$CI_PROJECT_NAME:latest
  INTERNAL_IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA

services:
  - docker:19.03.8-dind

stages:
  - build
  - test
  - push

include:
  - project: 'security/container-scanning'
    file: '.ESnet-container-scan.yml'

.build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $INTERNAL_IMAGE_TAG .
    - docker push $INTERNAL_IMAGE_TAG
  timeout: 2h

.push:
  stage: push
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $INTERNAL_IMAGE_TAG
    - docker tag $INTERNAL_IMAGE_TAG $PUBLISH_TAG
    - docker push $PUBLISH_TAG
    - if [ "${PUBLISH_LATEST}" == "true" ]; then docker tag $INTERNAL_IMAGE_TAG $LATEST_TAG && docker push $LATEST_TAG; fi
  timeout: 2h

build_image:
  extends: .build

# publish_develop:
#   extends: .push
#   variables:
#     PUBLISH_TAG: $ESNET_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_SHA
#     GIT_STRATEGY: none

# publish_release:
#   extends: .push
#   rules:
#     - if: '$CI_COMMIT_BRANCH == $RELEASE_BRANCH'
#     - if: $CI_COMMIT_TAG
#   variables:
#     PUBLISH_TAG: $ESNET_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
#     PUBLISH_LATEST: "true"
#     GIT_STRATEGY: none
