image: docker:20.10.10

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERT_DIR: ""
  INTERNAL_IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA

services:
  - docker:20.10.10-dind

stages:
  - build
  - test

default:
  tags:
    - ht-docker

container_scanning:
  variables:
    TRIVY_TIMEOUT: "1h"

include:
  - project: 'security/container-scanning'
    file: '.ESnet-container-scan.yml'

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $INTERNAL_IMAGE_TAG .
    - docker push $INTERNAL_IMAGE_TAG
  timeout: 3h
